// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Filter options for querying beans
type BeanFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	Search *string `json:"search,omitempty"`
	// Include only beans with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude beans with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only beans with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude beans with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only beans with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude beans with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only beans with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude beans with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only beans with a parent
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only beans with this specific parent ID
	ParentID *string `json:"parentId,omitempty"`
	// Include only beans that are blocking other beans
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only beans that are blocking this specific bean ID
	BlockingID *string `json:"blockingId,omitempty"`
	// Include only beans that are blocked by others
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Exclude beans that have a parent
	NoParent *bool `json:"noParent,omitempty"`
	// Exclude beans that are blocking other beans
	NoBlocking *bool `json:"noBlocking,omitempty"`
}

// Input for creating a new bean
type CreateBeanInput struct {
	// Bean title (required)
	Title string `json:"title"`
	// Bean type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Parent bean ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Bean IDs this bean is blocking
	Blocking []string `json:"blocking,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// Input for updating an existing bean
type UpdateBeanInput struct {
	// New title
	Title *string `json:"title,omitempty"`
	// New status
	Status *string `json:"status,omitempty"`
	// New type
	Type *string `json:"type,omitempty"`
	// New priority
	Priority *string `json:"priority,omitempty"`
	// Replace all tags (nil preserves existing)
	Tags []string `json:"tags,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
}
