package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/base64"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/hmans/beans/internal/agent"
	"github.com/hmans/beans/internal/gitutil"
	"github.com/hmans/beans/internal/graph/model"
	"github.com/hmans/beans/internal/worktree"
	"github.com/hmans/beans/pkg/bean"
	"github.com/hmans/beans/pkg/beancore"
	"github.com/hmans/beans/pkg/config"
)

// IsDirty is the resolver for the isDirty field.
func (r *beanResolver) IsDirty(ctx context.Context, obj *bean.Bean) (bool, error) {
	return r.Core.IsDirty(obj.ID), nil
}

// WorktreeID is the resolver for the worktreeId field.
func (r *beanResolver) WorktreeID(ctx context.Context, obj *bean.Bean) (*string, error) {
	wtPath := r.Core.WorktreeForBean(obj.ID)
	if wtPath == "" {
		return nil, nil
	}
	// Extract worktree ID from the path (last path component)
	id := filepath.Base(wtPath)
	return &id, nil
}

// ParentID is the resolver for the parentId field.
func (r *beanResolver) ParentID(ctx context.Context, obj *bean.Bean) (*string, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	return &obj.Parent, nil
}

// BlockingIds is the resolver for the blockingIds field.
func (r *beanResolver) BlockingIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return obj.Blocking, nil
}

// BlockedByIds is the resolver for the blockedByIds field.
func (r *beanResolver) BlockedByIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return obj.BlockedBy, nil
}

// BlockedBy is the resolver for the blockedBy field.
// Combines both directions: the bean's own blocked_by field AND incoming
// blocking links (other beans that list this bean in their blocking field).
func (r *beanResolver) BlockedBy(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	seen := make(map[string]bool)
	var result []*bean.Bean

	// 1. Resolve beans from the direct blocked_by field
	for _, blockerID := range obj.BlockedBy {
		if !seen[blockerID] {
			seen[blockerID] = true
			if blocker, err := r.Core.Get(blockerID); err == nil {
				result = append(result, blocker)
			}
		}
	}

	// 2. Resolve beans from incoming blocking links (other beans blocking this one)
	incoming := r.Core.FindIncomingLinks(obj.ID)
	for _, link := range incoming {
		if link.LinkType == "blocking" && !seen[link.FromBean.ID] {
			seen[link.FromBean.ID] = true
			result = append(result, link.FromBean)
		}
	}

	filtered := ApplyFilter(result, filter, r.Core)
	cfg := r.Core.Config()
	bean.SortByStatusPriorityAndType(filtered, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())
	return filtered, nil
}

// Blocking is the resolver for the blocking field.
func (r *beanResolver) Blocking(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	var result []*bean.Bean
	for _, targetID := range obj.Blocking {
		// Filter out broken links
		if target, err := r.Core.Get(targetID); err == nil {
			result = append(result, target)
		}
	}
	filtered := ApplyFilter(result, filter, r.Core)
	cfg := r.Core.Config()
	bean.SortByStatusPriorityAndType(filtered, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())
	return filtered, nil
}

// Parent is the resolver for the parent field.
func (r *beanResolver) Parent(ctx context.Context, obj *bean.Bean) (*bean.Bean, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	// Filter out broken links
	parent, err := r.Core.Get(obj.Parent)
	if err == beancore.ErrNotFound {
		return nil, nil
	}
	return parent, err
}

// Children is the resolver for the children field.
func (r *beanResolver) Children(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	incoming := r.Core.FindIncomingLinks(obj.ID)
	var result []*bean.Bean
	for _, link := range incoming {
		if link.LinkType == "parent" {
			result = append(result, link.FromBean)
		}
	}
	filtered := ApplyFilter(result, filter, r.Core)
	cfg := r.Core.Config()
	bean.SortByStatusPriorityAndType(filtered, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())
	return filtered, nil
}

// ImplicitStatus is the resolver for the implicitStatus field.
func (r *beanResolver) ImplicitStatus(ctx context.Context, obj *bean.Bean) (*string, error) {
	status, _ := r.Core.ImplicitStatus(obj.ID)
	if status == "" {
		return nil, nil
	}
	return &status, nil
}

// ImplicitStatusFrom is the resolver for the implicitStatusFrom field.
func (r *beanResolver) ImplicitStatusFrom(ctx context.Context, obj *bean.Bean) (*string, error) {
	_, fromID := r.Core.ImplicitStatus(obj.ID)
	if fromID == "" {
		return nil, nil
	}
	return &fromID, nil
}

// CreateBean is the resolver for the createBean field.
func (r *mutationResolver) CreateBean(ctx context.Context, input model.CreateBeanInput) (*bean.Bean, error) {
	b := &bean.Bean{
		Slug:     bean.Slugify(input.Title),
		Title:    input.Title,
		Type:     "task", // default
		Blocking: []string{},
	}

	// Optional fields with defaults documented in schema
	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Body != nil {
		b.Body = *input.Body
	}
	if len(input.Tags) > 0 {
		b.Tags = input.Tags
	}

	// Handle parent (with validation)
	if input.Parent != nil && *input.Parent != "" {
		// Normalise short ID to full ID
		parentID, _ := r.Core.NormalizeID(*input.Parent)
		if err := r.Core.ValidateParent(b, parentID); err != nil {
			return nil, err
		}
		b.Parent = parentID
	}

	// Handle blocking (with validation)
	if len(input.Blocking) > 0 {
		// Normalise short IDs to full IDs
		normalizedBlocking := make([]string, len(input.Blocking))
		for i, id := range input.Blocking {
			normalizedBlocking[i], _ = r.Core.NormalizeID(id)
			// Verify target exists
			if _, err := r.Core.Get(normalizedBlocking[i]); err != nil {
				return nil, fmt.Errorf("target bean not found: %s", id)
			}
		}
		b.Blocking = normalizedBlocking
	}

	// Handle blocked_by (with cycle validation)
	if len(input.BlockedBy) > 0 {
		// Normalise short IDs to full IDs
		normalizedBlockedBy := make([]string, len(input.BlockedBy))
		for i, id := range input.BlockedBy {
			normalizedBlockedBy[i], _ = r.Core.NormalizeID(id)
			// Verify blocker exists
			if _, err := r.Core.Get(normalizedBlockedBy[i]); err != nil {
				return nil, fmt.Errorf("blocker bean not found: %s", id)
			}
		}
		// Check for cycles with blocking relationships
		// (new bean being blocked_by X means X→newBean, check if newBean→X exists via blocking)
		for _, blockerID := range normalizedBlockedBy {
			for _, blockingID := range b.Blocking {
				if blockerID == blockingID {
					return nil, fmt.Errorf("would create cycle: new bean both blocks and is blocked by %s", blockerID)
				}
			}
		}
		b.BlockedBy = normalizedBlockedBy
	}

	// Handle custom prefix - pre-generate ID if prefix is provided
	if input.Prefix != nil && *input.Prefix != "" {
		idLength := 4 // default
		if cfg := r.Core.Config(); cfg != nil && cfg.Beans.IDLength > 0 {
			idLength = cfg.Beans.IDLength
		}
		id, err := bean.NewID(*input.Prefix, idLength)
		if err != nil {
			return nil, fmt.Errorf("generating bean ID: %w", err)
		}
		b.ID = id
	}

	if err := r.Core.Create(b); err != nil {
		return nil, err
	}

	return b, nil
}

// UpdateBean is the resolver for the updateBean field.
func (r *mutationResolver) UpdateBean(ctx context.Context, id string, input model.UpdateBeanInput) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Validate body and bodyMod are mutually exclusive
	if input.Body != nil && input.BodyMod != nil {
		return nil, fmt.Errorf("cannot specify both body and bodyMod")
	}

	// Validate tags and addTags/removeTags are mutually exclusive
	if input.Tags != nil && (input.AddTags != nil || input.RemoveTags != nil) {
		return nil, fmt.Errorf("cannot specify both tags and addTags/removeTags")
	}

	// Update fields if provided
	if input.Title != nil {
		b.Title = *input.Title
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Order != nil {
		b.Order = *input.Order
	}
	if input.Body != nil {
		b.Body = *input.Body
	} else if input.BodyMod != nil {
		// Apply body modifications
		workingBody := b.Body

		// Apply replacements sequentially
		if input.BodyMod.Replace != nil {
			for i, replaceOp := range input.BodyMod.Replace {
				newBody, err := bean.ReplaceOnce(workingBody, replaceOp.Old, replaceOp.New)
				if err != nil {
					return nil, fmt.Errorf("replacement %d failed: %w", i, err)
				}
				workingBody = newBody
			}
		}

		// Apply append if provided
		if input.BodyMod.Append != nil && *input.BodyMod.Append != "" {
			workingBody = bean.AppendWithSeparator(workingBody, *input.BodyMod.Append)
		}

		b.Body = workingBody
	}
	// Handle tags
	if input.Tags != nil {
		b.Tags = input.Tags
	} else if input.AddTags != nil || input.RemoveTags != nil {
		// Build a set of current tags
		tagSet := make(map[string]bool)
		for _, tag := range b.Tags {
			tagSet[tag] = true
		}

		// Add new tags
		if input.AddTags != nil {
			for _, tag := range input.AddTags {
				tagSet[tag] = true
			}
		}

		// Remove tags
		if input.RemoveTags != nil {
			for _, tag := range input.RemoveTags {
				delete(tagSet, tag)
			}
		}

		// Convert back to slice
		newTags := make([]string, 0, len(tagSet))
		for tag := range tagSet {
			newTags = append(newTags, tag)
		}
		b.Tags = newTags
	}

	// Handle parent relationship
	if input.Parent != nil {
		if err := r.validateAndSetParent(b, *input.Parent); err != nil {
			return nil, err
		}
	}

	// Handle blocking relationships
	if input.AddBlocking != nil {
		if err := r.validateAndAddBlocking(b, input.AddBlocking); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlocking != nil {
		r.removeBlockingRelationships(b, input.RemoveBlocking)
	}

	// Handle blocked-by relationships
	if input.AddBlockedBy != nil {
		if err := r.validateAndAddBlockedBy(b, input.AddBlockedBy); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlockedBy != nil {
		r.removeBlockedByRelationships(b, input.RemoveBlockedBy)
	}

	// ETag validation now happens inside Update() under write lock.
	// If the bean is linked to a worktree, Core auto-routes the write there.
	if err := r.Core.Update(b, input.IfMatch); err != nil {
		return nil, err
	}

	return b, nil
}

// DeleteBean is the resolver for the deleteBean field.
func (r *mutationResolver) DeleteBean(ctx context.Context, id string) (bool, error) {
	// Verify bean exists
	_, err := r.Core.Get(id)
	if err != nil {
		return false, err
	}

	// Remove incoming links first
	if _, err := r.Core.RemoveLinksTo(id); err != nil {
		return false, err
	}

	// Delete the bean
	if err := r.Core.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// SetParent is the resolver for the setParent field.
func (r *mutationResolver) SetParent(ctx context.Context, id string, parentID *string, ifMatch *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	newParent := ""
	if parentID != nil {
		// Normalise short ID to full ID
		newParent, _ = r.Core.NormalizeID(*parentID)
	}

	// Validate parent type hierarchy
	if newParent != "" {
		if err := r.Core.ValidateParent(b, newParent); err != nil {
			return nil, err
		}
		// Check for cycles
		if cycle := r.Core.DetectCycle(b.ID, "parent", newParent); cycle != nil {
			return nil, fmt.Errorf("would create cycle: %v", cycle)
		}
	}

	b.Parent = newParent
	// ETag validation now happens inside Update() under write lock
	if err := r.Core.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// AddBlocking is the resolver for the addBlocking field.
func (r *mutationResolver) AddBlocking(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, _ := r.Core.NormalizeID(targetID)

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("bean cannot block itself")
	}

	// Check target exists
	if _, err := r.Core.Get(normalizedTargetID); err != nil {
		return nil, fmt.Errorf("target bean not found: %s", targetID)
	}

	// Check for cycles in both directions:
	// 1. Check if targetId already has a path to id via blocking links
	if cycle := r.Core.DetectCycle(b.ID, "blocking", normalizedTargetID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}
	// 2. Check if targetId already has a path to id via blocked_by links
	if cycle := r.Core.DetectCycle(normalizedTargetID, "blocked_by", b.ID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	b.AddBlocking(normalizedTargetID)
	// ETag validation now happens inside Update() under write lock
	if err := r.Core.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// RemoveBlocking is the resolver for the removeBlocking field.
func (r *mutationResolver) RemoveBlocking(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, _ := r.Core.NormalizeID(targetID)

	b.RemoveBlocking(normalizedTargetID)
	// ETag validation now happens inside Update() under write lock
	if err := r.Core.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// AddBlockedBy is the resolver for the addBlockedBy field.
func (r *mutationResolver) AddBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, _ := r.Core.NormalizeID(targetID)

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("bean cannot be blocked by itself")
	}

	// Check target exists
	if _, err := r.Core.Get(normalizedTargetID); err != nil {
		return nil, fmt.Errorf("blocker bean not found: %s", targetID)
	}

	// Check for cycles in both directions:
	// 1. Check if targetId already has a path to id via blocking links
	if cycle := r.Core.DetectCycle(normalizedTargetID, "blocking", b.ID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}
	// 2. Check if id already has a path to targetId via blocked_by links
	if cycle := r.Core.DetectCycle(b.ID, "blocked_by", normalizedTargetID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	b.AddBlockedBy(normalizedTargetID)
	// ETag validation now happens inside Update() under write lock
	if err := r.Core.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// RemoveBlockedBy is the resolver for the removeBlockedBy field.
func (r *mutationResolver) RemoveBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, _ := r.Core.NormalizeID(targetID)

	b.RemoveBlockedBy(normalizedTargetID)
	// ETag validation now happens inside Update() under write lock
	if err := r.Core.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// WriteTerminalInput is the resolver for the writeTerminalInput field.
// Creates the session on demand if it doesn't exist yet.
func (r *mutationResolver) WriteTerminalInput(ctx context.Context, sessionID string, data string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, fmt.Errorf("terminal support not available")
	}

	sess := r.TerminalMgr.Get(sessionID)
	if sess == nil {
		// Session doesn't exist yet — create it on demand so callers
		// don't need to race against the terminal pane's WebSocket init.
		var workDir string
		if sessionID == CentralSessionID {
			workDir = r.ProjectRoot
		} else if r.WorktreeMgr != nil {
			workDir = r.WorktreeMgr.WorktreePath(sessionID)
		}
		if workDir == "" {
			return false, fmt.Errorf("terminal session %q not found and cannot resolve work dir", sessionID)
		}
		var err error
		sess, _, err = r.TerminalMgr.GetOrCreate(sessionID, workDir, 80, 24)
		if err != nil {
			return false, fmt.Errorf("failed to create terminal session: %w", err)
		}
	}

	if _, err := sess.Write([]byte(data)); err != nil {
		return false, fmt.Errorf("write to terminal: %w", err)
	}

	return true, nil
}

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, workspaceID string) (int, error) {
	if r.TerminalMgr == nil {
		return 0, fmt.Errorf("terminal support not available")
	}

	cfg := r.Core.Config()
	if cfg == nil || cfg.GetWorktreeRun() == "" {
		return 0, fmt.Errorf("no run command configured")
	}

	var workDir string
	if workspaceID == CentralSessionID {
		workDir = r.ProjectRoot
	} else if r.WorktreeMgr != nil {
		workDir = r.WorktreeMgr.WorktreePath(workspaceID)
	}
	if workDir == "" {
		return 0, fmt.Errorf("cannot resolve work directory for workspace %q", workspaceID)
	}

	sessionID := workspaceID + RunSessionSuffix
	if _, err := r.TerminalMgr.CreateWithCommand(sessionID, workDir, 80, 24, cfg.GetWorktreeRun()); err != nil {
		return 0, fmt.Errorf("failed to start run session: %w", err)
	}

	port := 0
	if r.PortAlloc != nil {
		if p, err := r.PortAlloc.Get(workspaceID); err == nil {
			port = p
		}
	}

	return port, nil
}

// StopRun is the resolver for the stopRun field.
func (r *mutationResolver) StopRun(ctx context.Context, workspaceID string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, fmt.Errorf("terminal support not available")
	}

	sessionID := workspaceID + RunSessionSuffix
	r.TerminalMgr.Close(sessionID)
	return true, nil
}

// CreateWorktree is the resolver for the createWorktree field.
func (r *mutationResolver) CreateWorktree(ctx context.Context, name string) (*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		return nil, fmt.Errorf("worktree support not available")
	}

	wt, err := r.WorktreeMgr.Create(name)
	if err != nil {
		return nil, err
	}

	// Allocate a workspace port for this worktree
	if r.PortAlloc != nil {
		r.PortAlloc.Allocate(wt.ID)
	}

	// Start watching the worktree's .beans/ directory for bean changes
	if err := r.Core.WatchWorktreeBeans(wt.Path); err != nil {
		fmt.Printf("[beans] warning: failed to watch worktree beans: %v\n", err)
	}

	return worktreeToModel(wt, r.Core, r.WorktreeMgr.BaseRef(), false), nil
}

// RemoveWorktree is the resolver for the removeWorktree field.
func (r *mutationResolver) RemoveWorktree(ctx context.Context, id string) (bool, error) {
	if r.WorktreeMgr == nil {
		return false, fmt.Errorf("worktree support not available")
	}

	// Find the worktree path before removing (for unwatching)
	worktrees, _ := r.WorktreeMgr.List()
	for _, wt := range worktrees {
		if wt.ID == id {
			r.Core.UnwatchWorktreeBeans(wt.Path)
			break
		}
	}

	if err := r.WorktreeMgr.Remove(id); err != nil {
		return false, err
	}

	// Free the workspace port
	if r.PortAlloc != nil {
		r.PortAlloc.Free(id)
	}

	// Close any terminal session associated with this worktree
	if r.TerminalMgr != nil {
		r.TerminalMgr.Close(id)
	}

	return true, nil
}

// SendAgentMessage is the resolver for the sendAgentMessage field.
func (r *mutationResolver) SendAgentMessage(ctx context.Context, beanID string, message string, images []*model.ImageInput) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}

	var workDir string
	if beanID == CentralSessionID {
		// Central agent chat runs in the project root
		workDir = r.ProjectRoot
	} else {
		// Find the worktree path for this bean
		var err error
		workDir, err = r.findWorktreePath(beanID)
		if err != nil {
			return false, err
		}
	}

	var uploads []agent.ImageUpload
	for _, img := range images {
		data, err := base64.StdEncoding.DecodeString(img.Data)
		if err != nil {
			return false, fmt.Errorf("invalid base64 image data: %w", err)
		}
		uploads = append(uploads, agent.ImageUpload{Data: data, MediaType: img.MediaType})
	}

	if err := r.AgentMgr.SendMessage(beanID, workDir, message, uploads); err != nil {
		return false, err
	}
	return true, nil
}

// StopAgent is the resolver for the stopAgent field.
func (r *mutationResolver) StopAgent(ctx context.Context, beanID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.StopSession(beanID); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentPlanMode is the resolver for the setAgentPlanMode field.
func (r *mutationResolver) SetAgentPlanMode(ctx context.Context, beanID string, planMode bool) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetPlanMode(beanID, planMode); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentActMode is the resolver for the setAgentActMode field.
func (r *mutationResolver) SetAgentActMode(ctx context.Context, beanID string, actMode bool) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetActMode(beanID, actMode); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentEffort is the resolver for the setAgentEffort field.
func (r *mutationResolver) SetAgentEffort(ctx context.Context, beanID string, effort string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetEffort(beanID, effort); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentPendingInteraction is the resolver for the setAgentPendingInteraction field.
func (r *mutationResolver) SetAgentPendingInteraction(ctx context.Context, beanID string, typeArg model.InteractionType, planContent *string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	var itype agent.InteractionType
	switch typeArg {
	case model.InteractionTypeExitPlan:
		itype = agent.InteractionExitPlan
	case model.InteractionTypeEnterPlan:
		itype = agent.InteractionEnterPlan
	case model.InteractionTypeAskUser:
		itype = agent.InteractionAskUser
	}
	interaction := &agent.PendingInteraction{Type: itype}
	if planContent != nil {
		interaction.PlanContent = *planContent
	}
	if err := r.AgentMgr.SetPendingInteraction(beanID, interaction); err != nil {
		return false, err
	}
	return true, nil
}

// ClearAgentSession is the resolver for the clearAgentSession field.
func (r *mutationResolver) ClearAgentSession(ctx context.Context, beanID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.ClearSession(beanID); err != nil {
		return false, err
	}
	return true, nil
}

// ArchiveBean is the resolver for the archiveBean field.
func (r *mutationResolver) ArchiveBean(ctx context.Context, id string) (bool, error) {
	if err := r.Core.Archive(id); err != nil {
		return false, err
	}
	return true, nil
}

// SaveDirtyBeans is the resolver for the saveDirtyBeans field.
func (r *mutationResolver) SaveDirtyBeans(ctx context.Context) (int, error) {
	return r.Core.SaveDirty()
}

// SaveBean is the resolver for the saveBean field.
func (r *mutationResolver) SaveBean(ctx context.Context, id string) (bool, error) {
	if err := r.Core.SaveBean(id); err != nil {
		return false, err
	}
	return true, nil
}

// ExecuteAgentAction is the resolver for the executeAgentAction field.
func (r *mutationResolver) ExecuteAgentAction(ctx context.Context, beanID string, actionID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}

	action := findAgentAction(actionID)
	if action == nil {
		return false, fmt.Errorf("unknown agent action: %s", actionID)
	}

	var workDir string
	if beanID == CentralSessionID {
		workDir = r.ProjectRoot
	} else {
		var err error
		workDir, err = r.findWorktreePath(beanID)
		if err != nil {
			return false, err
		}
	}

	actCtx := actionContext{WorktreeID: beanID, WorkDir: workDir, MainRepoPath: r.ProjectRoot}

	// Populate git state
	actCtx.HasChanges = gitutil.HasChanges(workDir)
	if r.WorktreeMgr != nil {
		actCtx.HasNewCommits = gitutil.HasUnmergedCommits(workDir, r.WorktreeMgr.BaseRef())
		actCtx.HasUnpushedCommits = gitutil.HasUnpushedCommits(workDir)
	}

	// Populate forge/PR state
	if r.Forge != nil {
		actCtx.ForgeCLI = r.Forge.CLIName()
		if branch, ok := gitutil.CurrentBranch(workDir); ok {
			pr, _ := r.Forge.FindPR(ctx, r.ProjectRoot, branch)
			actCtx.PullRequest = pr
		}
	}

	if err := r.AgentMgr.SendMessage(beanID, workDir, action.PromptFunc(actCtx), nil); err != nil {
		return false, err
	}
	return true, nil
}

// DiscardFileChange is the resolver for the discardFileChange field.
func (r *mutationResolver) DiscardFileChange(ctx context.Context, filePath string, staged bool, path *string) (bool, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return false, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return false, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	if err := gitutil.DiscardFileChange(dir, filePath, staged); err != nil {
		return false, err
	}
	return true, nil
}

// OpenInEditor is the resolver for the openInEditor field.
func (r *mutationResolver) OpenInEditor(ctx context.Context, workspaceID string) (bool, error) {
	var dir string
	if workspaceID == CentralSessionID {
		dir = r.ProjectRoot
	} else {
		if r.WorktreeMgr == nil {
			return false, fmt.Errorf("worktree support not available")
		}
		wts, err := r.WorktreeMgr.List()
		if err != nil {
			return false, err
		}
		for _, wt := range wts {
			if wt.ID == workspaceID {
				dir = wt.Path
				break
			}
		}
		if dir == "" {
			return false, fmt.Errorf("worktree not found: %s", workspaceID)
		}
	}

	cmd := exec.Command("code", dir)
	if err := cmd.Start(); err != nil {
		return false, fmt.Errorf("failed to open editor: %w", err)
	}
	// Don't wait for the process — VS Code detaches itself
	go cmd.Wait()

	return true, nil
}

// Bean is the resolver for the bean field.
func (r *queryResolver) Bean(ctx context.Context, id string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err == beancore.ErrNotFound {
		return nil, nil
	}
	return b, err
}

// Beans is the resolver for the beans field.
func (r *queryResolver) Beans(ctx context.Context, filter *model.BeanFilter) ([]*bean.Bean, error) {
	var beans []*bean.Bean

	// If search filter is provided, start with search results
	if filter != nil && filter.Search != nil && *filter.Search != "" {
		searchResults, err := r.Core.Search(*filter.Search)
		if err != nil {
			return nil, err
		}
		beans = searchResults
	} else {
		beans = r.Core.All()
	}

	result := ApplyFilter(beans, filter, r.Core)

	// Sort using the same logic as CLI and TUI
	cfg := r.Core.Config()
	bean.SortByStatusPriorityAndType(result, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())

	return result, nil
}

// Worktrees is the resolver for the worktrees field.
func (r *queryResolver) Worktrees(ctx context.Context) ([]*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		return []*model.Worktree{}, nil
	}

	wts, err := r.WorktreeMgr.List()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Worktree, len(wts))
	for i, wt := range wts {
		result[i] = worktreeToModel(&wt, r.Core, r.WorktreeMgr.BaseRef(), true)
	}
	populatePRsBatch(ctx, result, r.Forge, r.ProjectRoot)
	return result, nil
}

// AgentSession is the resolver for the agentSession field.
func (r *queryResolver) AgentSession(ctx context.Context, beanID string) (*model.AgentSession, error) {
	if r.AgentMgr == nil {
		return nil, nil
	}
	s := r.AgentMgr.GetSession(beanID)
	if s == nil {
		return nil, nil
	}
	return agentSessionToModel(s), nil
}

// FileChanges is the resolver for the fileChanges field.
func (r *queryResolver) FileChanges(ctx context.Context, path *string) ([]*model.FileChange, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		// Validate the path is a known worktree to prevent arbitrary filesystem access
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	changes, err := gitutil.FileChanges(dir)
	if err != nil {
		return nil, err
	}

	result := make([]*model.FileChange, len(changes))
	for i, c := range changes {
		result[i] = &model.FileChange{
			Path:      c.Path,
			Status:    c.Status,
			Additions: c.Additions,
			Deletions: c.Deletions,
			Staged:    c.Staged,
		}
	}
	return result, nil
}

// AllFileChanges is the resolver for the allFileChanges field.
func (r *queryResolver) AllFileChanges(ctx context.Context, path *string) ([]*model.FileChange, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}
	changes, err := gitutil.AllChangesVsUpstream(dir, baseRef)
	if err != nil {
		return nil, err
	}

	result := make([]*model.FileChange, len(changes))
	for i, c := range changes {
		result[i] = &model.FileChange{
			Path:      c.Path,
			Status:    c.Status,
			Additions: c.Additions,
			Deletions: c.Deletions,
			Staged:    c.Staged,
		}
	}
	return result, nil
}

// FileDiff is the resolver for the fileDiff field.
func (r *queryResolver) FileDiff(ctx context.Context, filePath string, staged bool, path *string) (string, error) {
	// Sanitize filePath to prevent path traversal
	cleaned := filepath.Clean(filePath)
	if filepath.IsAbs(cleaned) || strings.HasPrefix(cleaned, "..") {
		return "", fmt.Errorf("invalid file path: %s", filePath)
	}

	dir := r.ProjectRoot
	if path != nil && *path != "" {
		// Validate the path is a known worktree to prevent arbitrary filesystem access
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return "", err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return "", fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	return gitutil.FileDiff(dir, filePath, staged)
}

// AllFileDiff is the resolver for the allFileDiff field.
func (r *queryResolver) AllFileDiff(ctx context.Context, filePath string, path *string) (string, error) {
	cleaned := filepath.Clean(filePath)
	if filepath.IsAbs(cleaned) || strings.HasPrefix(cleaned, "..") {
		return "", fmt.Errorf("invalid file path: %s", filePath)
	}

	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return "", err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return "", fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}
	return gitutil.AllFileDiff(dir, filePath, baseRef)
}

// BranchStatus is the resolver for the branchStatus field.
func (r *queryResolver) BranchStatus(ctx context.Context, path *string) (*model.BranchStatus, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}

	return &model.BranchStatus{
		CommitsBehind: gitutil.CommitsBehind(dir, baseRef),
		HasConflicts:  gitutil.HasConflicts(dir, baseRef),
	}, nil
}

// HasDirtyBeans is the resolver for the hasDirtyBeans field.
func (r *queryResolver) HasDirtyBeans(ctx context.Context) (bool, error) {
	return r.Core.HasDirty(), nil
}

// AgentActions is the resolver for the agentActions field.
func (r *queryResolver) AgentActions(ctx context.Context, beanID string, skipForge *bool) ([]*model.AgentAction, error) {
	// Build action context for visibility filtering
	actCtx := actionContext{WorktreeID: beanID}

	// Set integrate mode from config
	if cfg := r.Core.Config(); cfg != nil {
		actCtx.IntegrateMode = string(cfg.GetWorktreeIntegrate())
	} else {
		actCtx.IntegrateMode = string(config.IntegrateModeLocal)
	}

	// Check if this worktree exists and gather its state
	var branch string
	if r.WorktreeMgr != nil {
		actCtx.MainRepoHasChanges = gitutil.HasChanges(r.WorktreeMgr.RepoRoot())

		if wts, err := r.WorktreeMgr.List(); err == nil {
			for _, wt := range wts {
				if wt.ID == beanID {
					actCtx.WorkDir = wt.Path
					actCtx.HasChanges = gitutil.HasChanges(wt.Path)
					actCtx.HasNewCommits = gitutil.HasUnmergedCommits(wt.Path, r.WorktreeMgr.BaseRef())
					actCtx.HasUnpushedCommits = gitutil.HasUnpushedCommits(wt.Path)
					actCtx.HasConflicts = gitutil.HasConflicts(wt.Path, r.WorktreeMgr.BaseRef())
					branch = wt.Branch
					break
				}
			}
		}
	}

	// Populate forge context
	if r.Forge != nil {
		actCtx.ForgeCLI = r.Forge.CLIName()
		if skipForge != nil && *skipForge {
			// Show the PR button in loading state while the full fetch is pending
			actCtx.ForgeLoading = true
		} else if branch != "" {
			pr, _ := r.Forge.FindPR(ctx, r.ProjectRoot, branch)
			actCtx.PullRequest = pr
		}
	}

	var result []*model.AgentAction
	for _, a := range agentActions {
		if a.Visible != nil && !a.Visible(actCtx) {
			continue
		}
		label := a.Label
		if a.LabelFunc != nil {
			label = a.LabelFunc(actCtx)
		}
		desc := a.Description
		action := &model.AgentAction{
			ID:          a.ID,
			Label:       label,
			Description: &desc,
		}
		if a.Disabled != nil {
			if reason := a.Disabled(actCtx); reason != "" {
				action.Disabled = true
				action.DisabledReason = &reason
			}
		}
		result = append(result, action)
	}
	return result, nil
}

// ProjectName is the resolver for the projectName field.
func (r *queryResolver) ProjectName(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return "", nil
	}
	return cfg.GetProjectName(), nil
}

// MainBranch is the resolver for the mainBranch field.
func (r *queryResolver) MainBranch(ctx context.Context) (string, error) {
	if branch, ok := gitutil.CurrentBranch(r.ProjectRoot); ok {
		return branch, nil
	}
	return "main", nil
}

// AgentEnabled is the resolver for the agentEnabled field.
func (r *queryResolver) AgentEnabled(ctx context.Context) (bool, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return true, nil
	}
	return cfg.IsAgentEnabled(), nil
}

// WorktreeBaseRef is the resolver for the worktreeBaseRef field.
func (r *queryResolver) WorktreeBaseRef(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return config.DefaultWorktreeBaseRef, nil
	}
	return cfg.GetWorktreeBaseRef(), nil
}

// WorktreeRunCommand is the resolver for the worktreeRunCommand field.
func (r *queryResolver) WorktreeRunCommand(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return "", nil
	}
	return cfg.GetWorktreeRun(), nil
}

// WorkspacePort is the resolver for the workspacePort field.
func (r *queryResolver) WorkspacePort(ctx context.Context, workspaceID string) (int, error) {
	if r.PortAlloc == nil {
		return 0, nil
	}
	port, err := r.PortAlloc.Get(workspaceID)
	if err != nil {
		return 0, nil
	}
	return port, nil
}

// IsRunning is the resolver for the isRunning field.
func (r *queryResolver) IsRunning(ctx context.Context, workspaceID string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, nil
	}
	sessionID := workspaceID + RunSessionSuffix
	sess := r.TerminalMgr.Get(sessionID)
	if sess == nil {
		return false, nil
	}
	return sess.Alive(), nil
}

// WorktreeIntegrateMode is the resolver for the worktreeIntegrateMode field.
func (r *queryResolver) WorktreeIntegrateMode(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return string(config.IntegrateModeLocal), nil
	}
	return string(cfg.GetWorktreeIntegrate()), nil
}

// BeanChanged is the resolver for the beanChanged field.
func (r *subscriptionResolver) BeanChanged(ctx context.Context, includeInitial *bool) (<-chan *model.BeanChangeEvent, error) {
	// Subscribe to bean events from beancore
	eventCh, unsubscribe := r.Core.Subscribe()

	// Create buffered output channel for GraphQL to reduce backpressure on the
	// subscriber channel. Without buffering, the resolver blocks on sends to gqlgen's
	// WebSocket transport, which prevents draining eventCh and causes fanOut to drop events.
	out := make(chan *model.BeanChangeEvent, 64)

	// Start goroutine to forward events
	go func() {
		defer unsubscribe()
		defer close(out)

		// If includeInitial is true, emit all current beans as a single snapshot
		if includeInitial != nil && *includeInitial {
			beans := r.Core.All()
			cfg := r.Core.Config()
			bean.SortByStatusPriorityAndType(beans, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())

			select {
			case out <- &model.BeanChangeEvent{
				Type:  model.ChangeTypeInitialSnapshot,
				Beans: beans,
			}:
				// Sent successfully
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				// Client disconnected
				return
			case events, ok := <-eventCh:
				if !ok {
					// Channel closed (watcher stopped)
					return
				}

				// Forward each event to the GraphQL subscription
				for _, event := range events {
					gqlEvent := &model.BeanChangeEvent{
						BeanID: event.BeanID,
						Bean:   event.Bean,
					}

					// Convert event type
					switch event.Type {
					case beancore.EventCreated:
						gqlEvent.Type = model.ChangeTypeCreated
					case beancore.EventUpdated:
						gqlEvent.Type = model.ChangeTypeUpdated
					case beancore.EventDeleted:
						gqlEvent.Type = model.ChangeTypeDeleted
					}

					select {
					case out <- gqlEvent:
						// Sent successfully
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// WorktreesChanged is the resolver for the worktreesChanged field.
func (r *subscriptionResolver) WorktreesChanged(ctx context.Context) (<-chan []*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		out := make(chan []*model.Worktree)
		close(out)
		return out, nil
	}

	ch := r.WorktreeMgr.Subscribe()
	out := make(chan []*model.Worktree)

	// buildWorktreeList converts worktree structs to GraphQL models without PR data.
	buildWorktreeList := func(wts []worktree.Worktree) []*model.Worktree {
		result := make([]*model.Worktree, len(wts))
		for i, wt := range wts {
			result[i] = worktreeToModel(&wt, r.Core, r.WorktreeMgr.BaseRef(), false)
		}
		return result
	}

	// wg tracks in-flight populatePRsAsync goroutines so we can wait for them
	// to finish before closing the out channel, preventing send-on-closed-channel panics.
	var wg sync.WaitGroup

	// populatePRsAsync fetches PR data for all worktrees in a single batch query,
	// then re-emits the updated list on the output channel.
	populatePRsAsync := func(result []*model.Worktree) {
		defer wg.Done()
		if r.Forge == nil || len(result) == 0 {
			return
		}
		populatePRsBatch(ctx, result, r.Forge, r.ProjectRoot)
		select {
		case out <- result:
		case <-ctx.Done():
		}
	}

	go func() {
		defer r.WorktreeMgr.Unsubscribe(ch)
		defer close(out)
		defer wg.Wait()

		// Emit the current list immediately without PR data, then
		// fetch PR data in the background and re-emit.
		if wts, err := r.WorktreeMgr.List(); err == nil {
			result := buildWorktreeList(wts)
			select {
			case out <- result:
			case <-ctx.Done():
				return
			}
			wg.Add(1)
			go populatePRsAsync(result)
		}

		// Periodically re-fetch PR data so sidebar icons stay current
		// even when no worktree filesystem events occur.
		prTicker := time.NewTicker(30 * time.Second)
		defer prTicker.Stop()

		// refreshPRs fetches the current worktree list with PR data and emits it.
		refreshPRs := func() {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return
			}
			result := buildWorktreeList(wts)
			wg.Add(1)
			go populatePRsAsync(result)
		}

		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-ch:
				if !ok {
					return
				}
				wts, err := r.WorktreeMgr.List()
				if err != nil {
					continue
				}
				result := buildWorktreeList(wts)
				select {
				case out <- result:
				case <-ctx.Done():
					return
				}
				wg.Add(1)
				go populatePRsAsync(result)
			case <-prTicker.C:
				refreshPRs()
			}
		}
	}()

	return out, nil
}

// AgentSessionChanged is the resolver for the agentSessionChanged field.
func (r *subscriptionResolver) AgentSessionChanged(ctx context.Context, beanID string) (<-chan *model.AgentSession, error) {
	if r.AgentMgr == nil {
		out := make(chan *model.AgentSession)
		close(out)
		return out, nil
	}

	ch := r.AgentMgr.Subscribe(beanID)
	out := make(chan *model.AgentSession)

	go func() {
		defer r.AgentMgr.Unsubscribe(beanID, ch)
		defer close(out)

		// Emit current state immediately (if session exists)
		if s := r.AgentMgr.GetSession(beanID); s != nil {
			select {
			case out <- agentSessionToModel(s):
			case <-ctx.Done():
				return
			}
		}

		// Then emit on each change
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-ch:
				if !ok {
					return
				}
				s := r.AgentMgr.GetSession(beanID)
				var ms *model.AgentSession
				if s != nil {
					ms = agentSessionToModel(s)
				} else {
					// Session was cleared — send an empty session so the UI resets
					ms = &model.AgentSession{
						BeanID:    beanID,
						AgentType: "claude",
						Status:    model.AgentSessionStatusIdle,
						Messages:  []*model.AgentMessage{},
					}
				}
				select {
				case out <- ms:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// ActiveAgentStatuses is the resolver for the activeAgentStatuses field.
func (r *subscriptionResolver) ActiveAgentStatuses(ctx context.Context) (<-chan []*model.ActiveAgentStatus, error) {
	if r.AgentMgr == nil {
		out := make(chan []*model.ActiveAgentStatus)
		close(out)
		return out, nil
	}

	ch := r.AgentMgr.SubscribeGlobal()
	out := make(chan []*model.ActiveAgentStatus)

	go func() {
		defer r.AgentMgr.UnsubscribeGlobal(ch)
		defer close(out)

		// Emit current state immediately
		select {
		case out <- activeAgentsToModel(r.AgentMgr.ListRunningSessions()):
		case <-ctx.Done():
			return
		}

		// Then emit on each change
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- activeAgentsToModel(r.AgentMgr.ListRunningSessions()):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// WorkspaceStatuses is the resolver for the workspaceStatuses field.
func (r *subscriptionResolver) WorkspaceStatuses(ctx context.Context) (<-chan []*model.WorkspaceStatus, error) {
	out := make(chan []*model.WorkspaceStatus)

	go func() {
		defer close(out)

		var wtCh chan struct{}
		if r.WorktreeMgr != nil {
			wtCh = r.WorktreeMgr.Subscribe()
			defer r.WorktreeMgr.Unsubscribe(wtCh)
		}

		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()

		// Track last emitted state to avoid sending duplicates.
		type statusKey struct{ hasChanges, hasUnmergedCommits bool }
		var lastStatuses map[string]statusKey

		compute := func() []*model.WorkspaceStatus {
			var result []*model.WorkspaceStatus

			// Main workspace status
			result = append(result, &model.WorkspaceStatus{
				ID:         CentralSessionID,
				HasChanges: gitutil.HasChanges(r.ProjectRoot),
			})

			// Worktree statuses
			if r.WorktreeMgr != nil {
				baseRef := r.WorktreeMgr.BaseRef()
				if wts, err := r.WorktreeMgr.List(); err == nil {
					for _, wt := range wts {
						result = append(result, &model.WorkspaceStatus{
							ID:                 wt.ID,
							HasChanges:         gitutil.HasChanges(wt.Path),
							HasUnmergedCommits: gitutil.HasUnmergedCommits(wt.Path, baseRef),
						})
					}
				}
			}

			return result
		}

		changed := func(statuses []*model.WorkspaceStatus) bool {
			if len(statuses) != len(lastStatuses) {
				return true
			}
			for _, s := range statuses {
				prev, ok := lastStatuses[s.ID]
				if !ok || prev.hasChanges != s.HasChanges || prev.hasUnmergedCommits != s.HasUnmergedCommits {
					return true
				}
			}
			return false
		}

		emit := func() {
			statuses := compute()
			if !changed(statuses) {
				return
			}
			lastStatuses = make(map[string]statusKey, len(statuses))
			for _, s := range statuses {
				lastStatuses[s.ID] = statusKey{s.HasChanges, s.HasUnmergedCommits}
			}
			select {
			case out <- statuses:
			case <-ctx.Done():
			}
		}

		emit() // initial state

		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				emit()
			case _, ok := <-wtCh:
				if !ok {
					return
				}
				emit()
			}
		}
	}()

	return out, nil
}

// Bean returns BeanResolver implementation.
func (r *Resolver) Bean() BeanResolver { return &beanResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type beanResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
